Controllers films users
zoomja/java-filmorate pull request #3
Opened 2024-07-01 17:03 UTC by zoomja

2024-07-02 16:37 UTC, Fleaman777 requested changes
В целом, код хорошего качества, но есть несколько предложений по улучшению:

2024-07-02 16:37 UTC, Fleaman777 commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> -/**
Использование аннотаций @NotBlank и @Size - отличный выбор для валидации названия и описания фильма. Добавь проверку на null для поля duration.

2024-07-02 16:37 UTC, Fleaman777 commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    private void validateFilm(Film film) {
private методы должны идти после публичных, так при беглом просмотре класса, можно будет быстро понять, какой функционал он отдает наружу

2024-07-02 16:37 UTC, Fleaman777 commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        if (!film.getReleaseDate().isAfter(LocalDate.of(1895, 12, 28)))
LocalDate.of(1895, 12, 28) - можно вынести в константу, что бы было удобней управлять этим значением и использовать в разных местах

2024-07-02 16:37 UTC, Fleaman777 commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +        throw new NotFoundException("Пользователь с id = " + user.getId() + " не найден");
лучше добавть else для чистоты кода,
или инвертировать проверку users.containsKey(user.getId()) и соответственно в ней выкинуть эксепешен, тоже хорошо скажится на чтение кода

2024-07-02 16:37 UTC, Fleaman777 commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +
отличное решение через валидационные аннотации

2024-07-02 16:37 UTC, Fleaman777 commented on src/test/java/ru/yandex/practicum/filmorate/FilmTest.java
> +}
как вариант уменьшения дублирования кода, часть общей иницилизации фильма можно сделать в отдлельном методе, а потом его уже немного кастомизировать согласно тест кейсу

2024-07-08 16:54 UTC, zoomja commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> -/**
добавил

2024-07-08 16:56 UTC, zoomja commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    private void validateFilm(Film film) {
исправил

2024-07-08 17:03 UTC, zoomja commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        if (!film.getReleaseDate().isAfter(LocalDate.of(1895, 12, 28)))
сделал

2024-07-08 17:29 UTC, zoomja commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +        throw new NotFoundException("Пользователь с id = " + user.getId() + " не найден");
исправил

2024-07-08 17:36 UTC, closed without merging