Финальное задание спринта 11
zoomja/java-filmorate pull request #7
Opened 2024-07-19 18:36 UTC by zoomja

2024-07-20 18:01 UTC, Fleaman777 requested changes

2024-07-20 18:01 UTC, Fleaman777 commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryFilmStorage.java
> +    private void validateFilm(Film film) {
с валидацией может быть двоякая история, 
по хорошему, в слове storage/dao/repository не должно быть валидации объектов которые сохраняются в сторедж, она должна быть на уровне сервис, repository классы отвечают только за взаимодейстиве со стореджем - в этом заключается SRP принцип

но может быть ситуация когда на каких-то столбцах в талицах в БД стоят констреинты, которые по сути являются валидацией, но это обычно валидация на уровне БД и она просто дополняет основную на уровне сервис

здесь можно было бы спросить, к какому уровню относится эта валидация, но поскольку у нас БД нет, можно сказать что к слою сервис)

2024-07-20 18:01 UTC, Fleaman777 commented on src/main/java/ru/yandex/practicum/filmorate/storage/interfaces/FilmStorage.java
> +    Film putFilm(Film newFilm);
я лучше использовал бы что-то более очевидное и привычное для метода обновления - updateFilm

аналагично для юзера

2024-07-22 16:48 UTC, zoomja commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +                .limit(count > 0 ? count : 10)
исправил

2024-07-22 17:12 UTC, zoomja commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +        }
исправил

2024-07-22 17:12 UTC, zoomja commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +        }
исправил

2024-07-22 17:16 UTC, zoomja commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryFilmStorage.java
> +    private void validateFilm(Film film) {
Пока нет базы данных, было принято решение реализовать это так.

2024-07-22 17:18 UTC, zoomja commented on src/main/java/ru/yandex/practicum/filmorate/storage/interfaces/FilmStorage.java
> +    Film putFilm(Film newFilm);
исправил

2024-07-23 06:58 UTC, Fleaman777 approved these changes

2024-08-06 18:59 UTC, merged